### ISSUE TITLE
Test component with theme and plugin scaffolding

### ISSUE THREAD

**Issue by timwright12** [10up/component-reading-position#6]

**Comment by timwright12** [comment]
Using npm

**Comment by fabiankaegy** [comment]
I have tested this with the theme scaffold and it is working.

But I'm getting an error from eslint in the console:

```bash
ERROR in /Users/fabiankaegy/Development/component-reading-position/src/reading-position.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/Users/fabiankaegy/Development/component-reading-position/src/reading-position.js
  13:1  error  Parsing error: The keyword 'export' is reserved

✖ 1 problem (1 error, 0 warnings)
```

@timwright12 do you maybe have an idea why this error is showing up? I did a bit of research but found no real solution this far.

**Comment by fabiankaegy** [comment]
I have done more research into it and this appear to be something caused because of the way `npm link` works.
> Be careful! The resource is the resolved path of the file, which means symlinked resources are the real path not the symlink location. This is good to remember when using tools that symlink packages (like npm link), common conditions like /node_modules/ may inadvertently miss symlinked files. Note that you can turn off symlink resolving (so that resources are resolved to the symlink path) via resolve.symlinks.

https://webpack.js.org/configuration/module/#rule-conditions


I will explore further into how to work within these constraints to get it working properly

CC: @timwright12

**Comment by fabiankaegy** [comment]
As discussed in slack I have created a PR against the Theme Scaffold to add `node_modules` to the scaffold. 

https://github.com/10up/theme-scaffold/pull/184

With that added it works as expected in the scaffolding.
