### ISSUE TITLE
Incorrect entry file in package.json

### ISSUE THREAD

**Issue by ivankruchkoff** [10up/component-reading-position#8]
**Describe the bug**
Incorrect entry file in JS, links to src, but should use transpiled version in dist.
https://github.com/10up/component-reading-position/blob/8ce30e9/package.json#L6

Causing this issue in downstream dependencies: 10up/theme-scaffold#183

**Comment by timwright12** [comment]
@fabiankaegy this one can be fixed since we haven't released yet

**Comment by fabiankaegy** [comment]
@timwright12 I have created the PR for it #9

**Comment by timwright12** [comment]
@fabiankaegy this will need to be testing, see my comment in the PR
